.TH "Src Directory Reference" 3 "Fri Aug 14 2020" "Version 1" "NextionForSTM32" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Src Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBnexcore\&.c\fP"
.br
.ti -1c
.RI "file \fBnexserial\&.c\fP"
.br
.ti -1c
.RI "file \fButilities\&.c\fP"
.br
.in -1c
