.TH "Inc/global.h" 3 "Fri Aug 14 2020" "Version 1" "NextionForSTM32" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Inc/global.h
.SH SYNOPSIS
.br
.PP
\fC#include 'stm32f1xx_hal\&.h'\fP
.br
\fC#include 'config\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBM_2PI\fP   6\&.283185307179586f"
.br
.ti -1c
.RI "#define \fBM_PI\fP   3\&.14159265358979323846f"
.br
.ti -1c
.RI "#define \fBM_PI_2\fP   1\&.57079632679489661923f"
.br
.ti -1c
.RI "#define \fBM_ROOT2\fP   1\&.4142135623f"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef uint8_t \fBBool_t\fP"
.br
.ti -1c
.RI "typedef uint8_t \fBTaskStatus_t\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum { \fBFALSE\fP = 0, \fBTRUE\fP = !FALSE, \fBNEXCORE_ERROR_INVALID_OPERATION\fP = 0, \fBNEXCORE_ERROR_COMMUNICATION_PROBLEM\fP, \fBNEXCORE_ERROR_BUFFER_OVERFLOW\fP, \fBNEXCORE_ERROR_NO_RESPONSE\fP, \fBNEXCORE_ERROR_INVALID_RECV_MSG\fP }"
.br
.ti -1c
.RI "enum { \fBUNINIT\fP = 0, \fBREADY\fP, \fBOPERATING\fP, \fBNEXCORE_INFO_READY\fP = 0, \fBNEXCORE_INFO_INSTRUCTION_SUCCESSFUL\fP }"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define M_2PI   6\&.283185307179586f"

.SS "#define M_PI   3\&.14159265358979323846f"

.SS "#define M_PI_2   1\&.57079632679489661923f"

.SS "#define M_ROOT2   1\&.4142135623f"

.SH "Typedef Documentation"
.PP 
.SS "typedef uint8_t \fBBool_t\fP"

.SS "typedef uint8_t \fBTaskStatus_t\fP"

.SH "Enumeration Type Documentation"
.PP 
.SS "anonymous enum"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIFALSE \fP\fP
.TP
\fB\fITRUE \fP\fP
.TP
\fB\fINEXCORE_ERROR_INVALID_OPERATION \fP\fP
.TP
\fB\fINEXCORE_ERROR_COMMUNICATION_PROBLEM \fP\fP
.TP
\fB\fINEXCORE_ERROR_BUFFER_OVERFLOW \fP\fP
.TP
\fB\fINEXCORE_ERROR_NO_RESPONSE \fP\fP
.TP
\fB\fINEXCORE_ERROR_INVALID_RECV_MSG \fP\fP
.SS "anonymous enum"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIUNINIT \fP\fP
.TP
\fB\fIREADY \fP\fP
.TP
\fB\fIOPERATING \fP\fP
.TP
\fB\fINEXCORE_INFO_READY \fP\fP
.TP
\fB\fINEXCORE_INFO_INSTRUCTION_SUCCESSFUL \fP\fP
.SH "Author"
.PP 
Generated automatically by Doxygen for NextionForSTM32 from the source code\&.
