.TH "Inc/queue.h" 3 "Fri Aug 14 2020" "Version 1" "NextionForSTM32" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Inc/queue.h
.SH SYNOPSIS
.br
.PP
\fC#include 'global\&.h'\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBQueue_Buffer_t\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for NextionForSTM32 from the source code\&.
